function carregarModeloSelecionado() {
  const seletor = document.getElementById("seletorModelos");
  const modelo = seletor.value;

  let conteudo = "";

  switch (modelo) {
    case "modelo1":
      conteudo = `
FABIO SANDRINI BAPTISTA-CEO- 01. Presidente ;FABIO SANDRINI BAPTISTA-PRESIDENTE-PRESIDENTE
ANTONIO CAVALCANTI JUNIOR-CFO- 02. VP ;FABIO SANDRINI BAPTISTA-FINANCEIRO-FINANCEIRO
CESAR LEONEL DA SILVA NETO-COO- 02. VP ;FABIO SANDRINI BAPTISTA-COO-COO
MARCOS ROBERTO MORETTI DE ALMEIDA-COO- 02. VP ;FABIO SANDRINI BAPTISTA-COO-COO
FABIO PANHONI DE PAULA PEREIRA-DIRETOR M&A- 02. VP ;FABIO SANDRINI BAPTISTA-M&A-M&A
ALAN RICIERI GIANOTTI-DIRETOR EXECUTIVO RH- 02. VP ;FABIO SANDRINI BAPTISTA-RECURSOS HUMANOS-RECURSOS HUMANOS
MARISSANDRA LOEFF-DIRETOR(A) DE CSC- 03. Diretor ;FABIO SANDRINI BAPTISTA-CSC-CSC
GAUTHAMA NASSIF FREIRE DE SOUZA-DIRETOR EXEC. MERCADO E INTELIGENCIA- 03. Diretor ;FABIO SANDRINI BAPTISTA-DIRETOR EXEC-DIRETOR EXEC
LUIZ CLAUDIO FERREIRA GARCIA-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-NEGÓCIOS
HENRIQUE MASSUELLA SALVADOR-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS GRANDES CONTAS
HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
ADRIANO ALVES CROCCO-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-OPERAÇÕES
SERGIO PAULO EHRLICH-DIRETOR DE NEGOCIOS- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
ADRIANA CORROCHANO MORI-DIRETOR(A) JURIDICO-03. Diretor ;ANTONIO CAVALCANTI JUNIOR-JURÍDICO-JURÍDICO
FABIO DE MORAES JORGE-DIRETOR DE SUPRIMENTOS-03. Diretor ;THIAGO DINIZ SILVEIRA FOGACA-SUPRIMENTOS-SUPRIMENTOS
DENILSON MARCIO RODRIGUES-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-OPERAÇÕES
AMARILDO SANDRO DE MORAES-DIRETOR DE NEGOCIOS- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-DIRETOR CONTABIL E FISCAL-03. Diretor ;ANTONIO CAVALCANTI JUNIOR-CONTÁBIL E FISCAL-CONTÁBIL E FISCAL
MARCIO ANDRE MOSCOSO DA ROCHA-DIRETOR COMERCIAL- 03. Diretor ;AUGUSTO CESAR LOUREIRO DA SILVA-COMERCIAL-COMERCIAL
AUGUSTO CESAR LOUREIRO DA SILVA-DIRETOR- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
CLODOVIRGES NEVES DE AMORIM JUNIOR-DIRETOR DE CONTROLADORIA- 03. Diretor ;ANTONIO CAVALCANTI JUNIOR-CONTROLADORIA-CONTROLADORIA
AMILTON SARAIVA DA COSTA-DIRETOR DE NEGOCIOS- 03. Diretor ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
FABIO FERNANDES BORGES-DIRETOR DE NEGOCIOS- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-OPERAÇÕES
LUIZ MAURO NASCIMENTO REIS-DIRETOR DE NEGOCIOS- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-OPERAÇÕES
WASHINGTON GONCALO RODRIGUES VELOSO-DIRETOR DE NEGOCIOS- 03. Diretor ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-OPERAÇÕES
FREDERICO MELO DUARTE-DIRETOR DE NEGOCIOS- 03. Diretor ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-ÉTICA / TRIANGULO MG
FERNANDO DE SIQUEIRA FERREIRA-DIRETOR DE NEGOCIOS- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
LORENNA IZABELLY MACIEL TARGINO DAMASCEN-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS
LUIS CARLOS DA SILVA-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS MANUT
RUSLAM ZOREK-DIRETOR DE NEGOCIOS- 03. Diretor ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-NEGÓCIOS
FRANCISCO CARLOS DOS SANTOS-DIRETOR DE NEGOCIOS- 03. Diretor ;ADRIANO ALVES CROCCO-OPERAÇÕES-OPERAÇÕES
GUSTAVO HELLMEISTER BELLORIO-GER SR PROCESSOS E INTEGRAÇÕES- 04. Gerente Sr ;ANTONIO CAVALCANTI JUNIOR-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
WILIAM PINHO DA SILVA RODRIGUES-GER DE TI- 05. Gerente ;MARISSANDRA LOEFF-TI-TI
MARAISA ALBERTINI GOMES-GER GERAL AUD INTERNA E COMPLIANCE- 04. Gerente Sr ;FABIO SANDRINI BAPTISTA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
PAULO AFONSO RODRIGUES MARQUES-GERENTE SENIOR DE PROCESSOS - CSC-;MARISSANDRA LOEFF-MACRO PROCESSOS DE FOLHA-MACRO PROCESSOS DE FOLHA
ELAINE VENSIGUER DE QUEIROZ-GER DE TI- 05. Gerente ;MARISSANDRA LOEFF-PROJETOS-PROJETOS
GUILHERME HENRIQUE FIGUEREDO CRUVINEL-GER NEGOCIOS- 05. Gerente ;MAURICIO ALMEIDA DIAS-OPERAÇÕES-CLIENTE
ANDRE LUIZ GUIMARAES PEREIRA-GER NEGOCIOS- 05. Gerente ;THIAGO DINIZ SILVEIRA FOGACA-OPERAÇÕES-CLIENTE
LUIZ HENRIQUE RAMOS FERRAZ-GERENTE DE M&A- 05. Gerente ;FABIO PANHONI DE PAULA PEREIRA-M&A-M&A
LILIANA NUNES MELLO-GERENTE TECNICO SAUDE- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE
WALDENIR LEONEL GIACONTO-GER FINANCEIRO- 05. Gerente ;ANTONIO CAVALCANTI JUNIOR-FINANCEIRO-FINANCEIRO
MOAB AZEVEDO DA SILVA-GER NEGOCIOS- 05. Gerente ;LUIZ MAURO NASCIMENTO REIS-OPERAÇÕES-OPERAÇÕES
TALITA DE OLIVEIRA RODRIGUES CASTANHO-GER JURIDICO DE CONTRATOS- 05. Gerente ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO CONTRATO
CRISTINA PARDUBSZKY-GER COMERCIAL- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-LICITAÇÃO E CONTRATOS PÚBLICOS
EDNALDO BERNALDO DA ROCHA-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
RENATO ROSSETO JUNIOR-GER TECNICO- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-ANÁLISE DE RISCO-ANÁLISE DE RISCO
DEBORA ETTORI DO PRADO ACERBI-GER RECURSOS HUMANOS- 05. Gerente ;ALAN RICIERI GIANOTTI-DHO-DHO
RENATO ROVELO-GER DE SESMT- 05. Gerente ;MARISSANDRA LOEFF-SESMT-SESMT
MATEUS DE SOUZA SEHN-GER BI- 05. Gerente ;MARISSANDRA LOEFF-BI-BI
MARCELLO HUMBERTO CREMONEZI CHIAPPETTA-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
EMERSON ZANI-GER NEGOCIOS- 05. Gerente ;AMARILDO SANDRO DE MORAES-OPERAÇÕES-OPERAÇÕES
VICTOR MONTEIRO-GER NEGOCIOS- 05. Gerente ;ADRIANO ALVES CROCCO-OPERAÇÕES-OPERAÇÕES
JOSE JOSINALDO FERREIRA DOS SANTOS-GER PLANEJAMENTO- 05. Gerente ;LUIZ MAURO NASCIMENTO REIS-APOIO OPERACIONAL-TI
DIEGO COUREL MONTANARI-GER FISCAL- 05. Gerente ;MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-CONTÁBIL E FISCAL-FISCAL
HUAYNA ELOHIM PEREZ CONTRERAS-GER INTELIGENCIA DE MERCADO- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-INTELIGÊNCIA DE MERCADO-INTELIGÊNCIA DE MERCADO
BRUNO JEAN CARRERE-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
MARCIA APARECIDA FORSTER-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
TATIANE APARECIDA GUEDES MORAES-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
ELCINO ANTONIO BARBOSA-GER RECURSOS HUMANOS- 05. Gerente ;ALAN RICIERI GIANOTTI-RELAÇÕES SINDICAIS-RELAÇÕES SINDICAIS
APARECIDA BISPO ARAUJO TOMAZ-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
ROMULO SACRAMENTO VILELA-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
EDUARDO RODRIGUES BRANDAO-GER NEGOCIOS- 05. Gerente ;SERGIO PAULO EHRLICH-OPERAÇÕES-OPERAÇÕES
ERIKA CRISTINA GONCALVES VIEIRA-GER NEGOCIOS- 05. Gerente ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-NEGÓCIOS
PATRICIA GOMES DA SILVA-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
RICARDO CÉSAR DE OLIVEIRA FERREIRA-GER DE CONTROLADORIA- 05. Gerente ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA-CONTROLADORIA
AMANDA PEREIRA DA SILVA-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
KARINA MACHADO JARDIM-GER REMUNERAÇÃO E DESEMPENHO- 05. Gerente ;ALAN RICIERI GIANOTTI-REMUNERAÇÃO-REMUNERAÇÃO
SILVANIA DOS SANTOS RABELO-GER CONTRATO- 05. Gerente ;FERNANDO DE SIQUEIRA FERREIRA-COMERCIAL-COMERCIAL
DANIEL DE FREITAS SIQUEIRA-GERENTE DE DESENVOLVIMENTO E PLANEJAMENTO COMERCIAL- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO & DESENVOLVIMENTO
MARCELO GOMES DOS SANTOS-GER NEGOCIOS- 05. Gerente ;WASHINGTON GONCALO RODRIGUES VELOSO-OPERAÇÕES-OPERAÇÕES
NATALI RIBEIRO MILLAN HORCAIO-GER NEGOCIOS- 05. Gerente ;ADRIANO ALVES CROCCO-OPERAÇÕES-OPERAÇÕES
ROSINEI MOREIRA-GER RECURSOS HUMANOS- 05. Gerente ;MARISSANDRA LOEFF-PONTO E CONTROLE DE POSTOS-PONTO E CONTROLE DE POSTOS
VALERIA TONDATO-GER DE MACRO PROCESSO DE RH- 05. Gerente ;PAULO AFONSO RODRIGUES MARQUES-MACRO PROCESSOS DE FOLHA-BENEFÍCIO
DIRCE KARINA FERREIRA SOMENSARI-GER OPERACIONAL- 05. Gerente ;DIRCE KARINA FERREIRA SOMENSARI-OPERAÇÕES-CLIENTE
NATALIA CRISTINA DO CARMO GARCIA-GER COMUNICACAO E MARKETING- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-MARKETING E CX-MARKETING E CX
JOAO CARLOS DE SOUSA-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
CLAUDIA ALVES DOS SANTOS-GER COMERCIAL REGIONAL- 05. Gerente ;DENILSON MARCIO RODRIGUES-COMERCIAL-COMERCIAL
LUCIANA PIERRE-GER ORÇAMENTISTA- 08. Analista ;LUIS CARLOS DA SILVA-COMERCIAL-PRECIFICAÇÃO
THAIS DANIELLI GIMENEZ-GER JURIDICO- 05. Gerente ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO CONTENCIOSO
MELINA DUARTE MARINI LOPES-GER COMERCIAL- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE
JOSE AURELIO MOSSON-GERENTE DE FACILITIES- 05. Gerente ;THIAGO DINIZ SILVEIRA FOGACA-FACILITIES-FACILITIES
ADEMIR FERREIRA BUENO-GER NEGOCIOS- 05. Gerente ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-OPERAÇÕES
SOLANGE DO NASCIMENTO RAMOS GRILO-GER NEGOCIOS- 05. Gerente ;LUIZ CLAUDIO FERREIRA GARCIA-OPERAÇÕES-OPERAÇÕES
ALEXANDRE GONCALVES MAIA-GER COMERCIAL REGIONAL- 05. Gerente ;LUIZ CLAUDIO FERREIRA GARCIA-COMERCIAL-COMERCIAL
JOSE AQUILES FERREIRA DA SILVA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
CELSO CABRAL DE AMORIM-GER CONTRATO- 05. Gerente ;INACIO GOMES FREIRE FILHO-OPERAÇÕES-CLIENTE
NATHALIA VILLALTA SANTOS GRABALOS-GER COMERCIAL REGIONAL- 05. Gerente ;ADRIANO ALVES CROCCO-COMERCIAL-COMERCIAL
SIDNEI FRANCISCO INOCENCIO-GER NEGOCIOS- 05. Gerente ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-OPERAÇÕES
MILTON NALDI-GER COMERCIAL- 05. Gerente ;LUIS CARLOS DA SILVA-COMERCIAL-VENDAS
PATRICIA FINOTI DE OLIVEIRA-GER RECURSOS HUMANOS- 05. Gerente ;PAULO AFONSO RODRIGUES MARQUES-R&S-R&S
AMARILIS FELIPE FONSECA FERREIRA AYRES-GER NEGOCIOS- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-OPERAÇÕES-OPERAÇÕES
PRISCILA PEREIRA PINHEIRO-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
ADRIANA VIRGINIA DA SILVEIRA GALLO-GER NEGOCIOS- 05. Gerente ;ADRIANO ALVES CROCCO-OPERAÇÕES-OPERAÇÕES
DANIELLY LIMA DA SILVA BRAGA-GER RECURSOS HUMANOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-RECURSOS HUMANOS-RECURSOS HUMANOS
LIA SILVA DOS SANTOS-GER FINANCEIRO- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-FINANCEIRO-FATURAMENTO
JULIO BOTTURA-GER COMERCIAL REGIONAL- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-COMERCIAL-COMERCIAL
JAQUELINE RIBEIRO COSTA THOUIN-GER CONTRATO- 05. Gerente ;VICTOR MONTEIRO-OPERAÇÕES-CLIENTE
FERNANDA FELIX ALVES BARROS-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
FERNANDA FELIX ALVES BARROS-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
NATALIA FERREIRA MACHADO-GER CONTRATO- 05. Gerente ;STEPHANIA DE ALMEIDA BARBOSA-OPERAÇÕES-CLIENTE
WILSON NASCIMENTO SANTOS-GER NEGOCIOS- 05. Gerente ;RUSLAM ZOREK-OPERAÇÕES-OPERAÇÕES
MICHAEL BRUNO DA SILVA AUGUSTO-GER CONTRATO- 05. Gerente ;TIAGO GARCES DA SILVA-OPERAÇÕES-CLIENTE
RAFAEL DE SIQUEIRA VELOSO-GER COMERCIAL- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE E MANUT
RITA VERONESI PINTO-GER COMERCIAL- 05. Gerente ;LUIS CARLOS DA SILVA-COMERCIAL-VENDAS
DJANINE RODRIGUES DE SANTANA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
JULIANO TOGNOLI-GERENTE DE PRECIFICACAO E ADMINISTRACAO DE VENDAS-;GAUTHAMA NASSIF FREIRE DE SOUZA-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
ROSELI GAMA NORONHA DA MOTTA-GER RECURSOS HUMANOS- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-RECURSOS HUMANOS-RECURSOS HUMANOS
ROSELI GAMA NORONHA DA MOTTA-GER RECURSOS HUMANOS- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-RECURSOS HUMANOS-RECURSOS HUMANOS
RICARDO APARECIDO DOMINGUES PERES-GER COMERCIAL- 05. Gerente ;JULIO BOTTURA-COMERCIAL-VENDAS
FERNANDA ARCANJA DA MATA FORMIGARI-GER VENDAS- 05. Gerente ;HENRIQUE MASSUELLA SALVADOR-VENDAS-VENDAS GRANDES CONTAS
NATHALIA BONFIM DE SANTANA-GER COMERCIAL- 05. Gerente ;NATHALIA VILLALTA SANTOS GRABALOS-COMERCIAL-VENDAS
FABIANO DA SILVA CAMPOS-GER NEGOCIOS- 05. Gerente ;WASHINGTON GONCALO RODRIGUES VELOSO-OPERAÇÕES-OPERAÇÕES
RAUL FRANCISCO DELGADO-GER CONTRATO- 05. Gerente ;MISAEL LOPES SALES-OPERAÇÕES-CLIENTE
LUIZ FERNANDO LEME DE SOUZA-GER NEGOCIOS- 05. Gerente ;ADRIANO ALVES CROCCO-OPERAÇÕES-OPERAÇÕES
MAURICIO ALMEIDA DIAS-GER OPERACIONAL- 05. Gerente ;GUILHERME HENRIQUE FIGUEREDO CRUVINEL-OPERAÇÕES-CLIENTE
JUDITE MARIA DE ARAUJO-GER NEGOCIOS- 05. Gerente ;FABIO FERNANDES BORGES-OPERAÇÕES-OPERAÇÕES
FABIANO DA SILVA ALMEIDA-GER NEGOCIOS- 05. Gerente ;WASHINGTON GONCALO RODRIGUES VELOSO-OPERAÇÕES-OPERAÇÕES
ROSALY PREMAZZI-GER COMERCIAL- 05. Gerente ;ALEXANDRE GONCALVES MAIA-COMERCIAL-COMERCIAL
FRED EDUARDO CASTANHA BARRETO TENORIO-GER COMERCIAL REGIONAL- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-COMERCIAL-VENDAS
MARIO CONSTANTINO ATAIDE JUNIOR-GER COMERCIAL- 05. Gerente ;ALEXANDRE GONCALVES MAIA-COMERCIAL-VENDAS
JAQUELINE SANTOS SOARES MALTA-GER NEGOCIOS- 05. Gerente ;WASHINGTON GONCALO RODRIGUES VELOSO-OPERAÇÕES-OPERAÇÕES
EVERTON GUILHERME UCHOA RODRIGUES-GER CONTRATO- 05. Gerente ;DJANINE RODRIGUES DE SANTANA-OPERAÇÕES-CLIENTE
MAIARA RUIS PETRUCELLI-GER COMERCIAL- 05. Gerente ;NATHALIA VILLALTA SANTOS GRABALOS-COMERCIAL-VENDAS
DOMINGOS GALATI JUNIOR-GER COMERCIAL- 05. Gerente ;NATHALIA VILLALTA SANTOS GRABALOS-COMERCIAL-VENDAS
DIEGO PRADO MESQUITA VIANA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
ESTER FILGUEIRAS BUENO-GER CONTRATO- 05. Gerente ;ADEMIR FERREIRA BUENO-OPERAÇÕES-CLIENTE
CARLOS JUNIOR CARNEIRO DE SOUZA-GER COMERCIAL- 05. Gerente ;JULIO BOTTURA-COMERCIAL-VENDAS
DAGMAR APARECIDA ALOISI-GERENTE- 05. Gerente ;DIRCE KARINA FERREIRA SOMENSARI-OPERAÇÕES-CLIENTE
MARTA SERPA DE FARIAS-GER CONTRATO- 05. Gerente ;SIDNEI FRANCISCO INOCENCIO-OPERAÇÕES-CLIENTE
REINALDO HENRIQUE DE OLIVEIRA-GER COMERCIAL- 05. Gerente ;SILVANIA RABELO-COMERCIAL-VENDAS
JOÃO GABRIEL LEIRIÃO BARRETO-GER COMERCIAL- 05. Gerente ;SILVANIA RABELO-COMERCIAL-VENDAS
ARIANE CAMARGO REAL PRADO-GERENTE DE CONTAS-;AMILTON SARAIVA DA COSTA-VENDAS-VENDAS
MONIQUE CIBELLE SANTOS DA SILVA-GERENTE DE CONTAS-;FRED EDUARDO CASTANHA BARRETO TENORIO-COMERCIAL-VENDAS
ROGERIA FERREIRA BELARMINO -GERENTE- 05. Gerente ;SHARA INGRID DE SOUSA-OPERAÇÕES-CLIENTE
MARIANA VICTORIA SOBRINHO DE O LOBATO-GER OPERACIONAL- 05. Gerente ;LUCIANO LEONARDO DAS NEVES-OPERAÇÕES-CLIENTE
FELIPE PANDINO MACIEL-GER OPERACIONAL- 05. Gerente ;LUCIANO LEONARDO DAS NEVES-OPERAÇÕES-CLIENTE
ROSANIA PEIXOTO DA SILVA-GER CONTRATO- 05. Gerente ;MARCELO GOMES DOS SANTOS-OPERAÇÕES-CLIENTE
SERGIO HENRIQUE CHAVES-GERENTE- 05. Gerente ;ADEMIR FERREIRA BUENO-OPERAÇÕES-CLIENTE
RUAO FERNANDO CARLOS-GER CONTRATO- 05. Gerente ;ADEMIR FERREIRA BUENO-OPERAÇÕES-CLIENTE
FILIPE VILLALVA BARBOSA-MEDICO DO TRABALHO - COORDENADOR- 06. Coord. / Esp. ;RENATO ROVELO-SESMT-MEDICINA DO TRABALHO
OSVALDO LUCIANO DO AMARAL JÚNIOR-COORD M&A- 06. Coord. / Esp. ;LUIZ HENRIQUE RAMOS FERRAZ-M&A-M&A
THIAGO SANTOS PIELLUSCH TAVARES-COORD PRODUTOS E INOVACAO TI-;WILIAM PINHO DA SILVA RODRIGUES-TI-INOVAÇÃO DIGITAL
CAUÊ SOTO-COORD DE TI - INFRAESTRUTURA- 06. Coord. / Esp. ;WILIAM PINHO DA SILVA RODRIGUES-TI-INFRA & CYBER
ARLEN DA SILVA DOS SANTOS-COORD GOVERNANCA DE TI- 06. Coord. / Esp. ;WILIAM PINHO DA SILVA RODRIGUES-TI-GOVERNANÇA TI
JOSE DE SOUZA MAIA FILHO-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
RICARDO FERREIRA DOS SANTOS-COORD DE PROJETOS- 06. Coord. / Esp. ;GUSTAVO HELLMEISTER BELLORIO-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
CAROLINE DOMINGUES ORTOLANI-COORD DE FATURAMENTO - 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA-GARANTIA DA RECEITA
DANIELI APARECIDA ASSAF LEMES-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
PAOLA GIOVANNA FALASCA GALUTTI-COORD DE PROCESSOS- 06. Coord. / Esp. ;MARISSANDRA LOEFF-PROCESSOS-PROCESSOS
MAURO TADEU FAXINA-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
DANIEL MOREIRA CARVALHO-MEDICO DO TRABALHO- 08. Analista ;RENATA UMBELINO FERREIRA-SESMT-MEDICINA DO TRABALHO
FERNANDO NERIS DOS SANTOS-COORD COMPRAS- 06. Coord. / Esp. ;FABIO DE MORAES JORGE-SUPRIMENTOS-SUPRIMENTOS
WILLIAN MORENO PEDRO-COORD DE TI E PRODUTOS- 06. Coord. / Esp. ;FERNANDO DE SIQUEIRA FERREIRA-APOIO OPERACIONAL-TI
SORAYA DOS SANTOS DE ALMEIDA-COORD GOVERNANÇA RISCOS E COMP- 06. Coord. / Esp. ;MARAISA ALBERTINI GOMES-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
PRISCILA ALESSANDRA BAGO-COORD GESTAO DA MUDANCA- 06. Coord. / Esp. ;ALAN RICIERI GIANOTTI-GESTÃO DA MUDANÇA-GESTÃO DA MUDANÇA
RODRIGO LADISLAU SILVEIRA-COORD OPERACIONAL- 06. Coord. / Esp. ;INACIO GOMES FREIRE FILHO-OPERAÇÕES-CLIENTE
RAPHAEL MOTA VALENTIM-COORD DE MANUTENCAO- 06. Coord. / Esp. ;LUIZ MAURO NASCIMENTO REIS-OPERAÇÕES-OPERAÇÕES
MARIANA LIMA ZAPAROLLI-COORDENADOR DE DHO- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-TREINAMENTO E DESENVOLVIMENTO
ADRIANA FREITAS SIMAO-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;ADRIANO ALVES CROCCO-CONTROLADORIA/FINANÇAS-CONTROLADORIA
CHARLES JORGE FERREIRA-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;LUIZ CLAUDIO FERREIRA GARCIA-CONTROLADORIA/FINANÇAS-CONTROLADORIA
VICTOR HUGO DE OLIVEIRA BATISTA-COORD FINANCEIRO- 06. Coord. / Esp. ;WALDENIR LEONEL GIACONTO-FINANCEIRO-FINANCEIRO
JULIANA MALDONADO MELNICHENCO-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA/FINANÇAS-CONTROLADORIA
RENATA DE CARVALHO TOSTES-MEDICO DO TRABALHO- 08. Analista ;LUIZ CLAUDIO FERREIRA GARCIA-SESMT-MEDICINA DO TRABALHO
ALESSANDRO JOSE BORGES-COORD OPERACIONAL- 06. Coord. / Esp. ;FREDERICO MELO DUARTE-OPERAÇÕES-OPERAÇÕES
FILIPE VILLALVA BARBOSA-MEDICO DO TRABALHO- 08. Analista ;RENATO ROVELO-SESMT-MEDICINA DO TRABALHO
WELLINGTON GARCIA DOS SANTOS-COORD DE MANUTENCAO- 06. Coord. / Esp. ;TIAGO GARCES DA SILVA-OPERAÇÕES-CLIENTE
DENNIS SILVESTRIM DE FREITAS-COORD CONTABIL- 06. Coord. / Esp. ;MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-CONTÁBIL E FISCAL-CONTABIL
DANILO CASTRO ALVES-COORD POSTO- 06. Coord. / Esp. ;BRUNO JEAN CARRERE-OPERAÇÕES-CLIENTE
SHIRLEY PEREIRA DE MATTOS-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-CONTROLADORIA/FINANÇAS-CONTROLADORIA
SIMONI DE SOUZA VIEIRA-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-CONTROLADORIA/FINANÇAS-CONTROLADORIA
JOSE RICARDO MARTINS-COORDENADOR PREVIDENCIÁRIO- 06. Coord. / Esp. ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-PREVIDENCIÁRIO
MARLON PEREIRA DA SILVA-COORDENADOR DE O&M- 06. Coord. / Esp. ;MAURICIO ALMEIDA DIAS-OPERAÇÕES-CLIENTE
CAMILA NOGUEIRA DE ARAUJO-COORD ADMINISTRATIVO- 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-FINANCEIRO-CONTROLADORIA
RENATA ROCINHOLLI DE OLIVEIRA-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA/FINANÇAS-CONTROLADORIA
EDUARDO APARECIDO WAIANDT-COORD OPERACIONAL- 06. Coord. / Esp. ;ROMULO SACRAMENTO VILELA-OPERAÇÕES-OPERAÇÕES
FRANK CESAR VIEIRA DE SOUZA-COORDENADOR (A)- 06. Coord. / Esp. ;JONATHAN MOTA DE CARVALHO-OPERAÇÕES-CLIENTE
MARCELO PIRES DE QUEIROZ-COORD DE MANUTENCAO- 06. Coord. / Esp. ;TIAGO GARCES DA SILVA-OPERAÇÕES-CLIENTE
JOSE DE ASSIS OLIVEIRA-COORD DE MANUTENCAO- 06. Coord. / Esp. ;TIAGO GARCES DA SILVA-OPERAÇÕES-CLIENTE
RIVANILSON RIBEIRO SANTOS-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;TATIANE APARECIDA GUEDES MORAES-OPERAÇÕES-OPERAÇÕES
EDMILSON DOS SANTOS OLIVEIRA-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;TATIANE APARECIDA GUEDES MORAES-OPERAÇÕES-OPERAÇÕES
CAIO HENRIQUE MARQUES BUENO-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;EDUARDO RODRIGUES-OPERAÇÕES-OPERAÇÕES
TIAGO RODRIGUES DA COSTA-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;BRUNO JEAN CARRERE-OPERAÇÕES-OPERAÇÕES
CLEITON CANDIDO DA SILVA-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;EDNALDO BERNALDO DA ROCHA-OPERAÇÕES-OPERAÇÕES
ADEILDO CARLOS BEZERRA-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;BRUNO JEAN CARRERE-OPERAÇÕES-OPERAÇÕES
JOSE RICARDO PRATES ANDRADE-GESTOR DE SEGURANÇA- 06. Coord. / Esp. ;APARECIDA BISPO ARAUJO TOMAZ-OPERAÇÕES-OPERAÇÕES

`;
      break;
    case "modelo2":
      conteudo = `
FABIO SANDRINI BAPTISTA-CEO- 01. Presidente ;FABIO SANDRINI BAPTISTA-PRESIDENTE-PRESIDENTE
CESAR LEONEL DA SILVA NETO-COO- 02. VP ;FABIO SANDRINI BAPTISTA-COO-COO
MARAISA ALBERTINI GOMES-GER GERAL AUD INTERNA E COMPLIANCE- 04. Gerente Sr ;FABIO SANDRINI BAPTISTA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
ALAN RICIERI GIANOTTI-DIRETOR EXECUTIVO RH- 02. VP ;FABIO SANDRINI BAPTISTA-RECURSOS HUMANOS-RECURSOS HUMANOS
GAUTHAMA NASSIF FREIRE DE SOUZA-DIRETOR EXEC. MERCADO E INTELIGENCIA- 03. Diretor ;FABIO SANDRINI BAPTISTA-DIRETOR EXEC-DIRETOR EXEC
MARISSANDRA LOEFF-DIRETOR(A) DE CSC- 03. Diretor ;FABIO SANDRINI BAPTISTA-CSC-CSC
FABIO PANHONI DE PAULA PEREIRA-DIRETOR M&A- 02. VP ;FABIO SANDRINI BAPTISTA-M&A-M&A
ANTONIO CAVALCANTI JUNIOR-CFO- 02. VP ;FABIO SANDRINI BAPTISTA-FINANCEIRO-FINANCEIRO
MARCOS ROBERTO MORETTI DE ALMEIDA-COO- 02. VP ;FABIO SANDRINI BAPTISTA-COO-COO
THIAGO DINIZ SILVEIRA FOGACA-DIRETOR EFICIÊNCIA-  02. VP;FABIO SANDRINI BAPTISTA-EFICIÊNCIA-EFICIÊNCIA


`;
      break;
    case "modelo3":
      conteudo = `
ALAN RICIERI GIANOTTI-DIRETOR EXECUTIVO RH- 02. VP ;FABIO SANDRINI BAPTISTA-RECURSOS HUMANOS-RECURSOS HUMANOS
DEBORA ETTORI DO PRADO ACERBI-GER RECURSOS HUMANOS- 05. Gerente ;ALAN RICIERI GIANOTTI-DHO-DHO
ELCINO ANTONIO BARBOSA-GER RECURSOS HUMANOS- 05. Gerente ;ALAN RICIERI GIANOTTI-RELAÇÕES SINDICAIS-RELAÇÕES SINDICAIS
KARINA MACHADO JARDIM-GER REMUNERAÇÃO E DESEMPENHO- 05. Gerente ;ALAN RICIERI GIANOTTI-REMUNERAÇÃO-REMUNERAÇÃO
PRISCILA ALESSANDRA BAGO-COORD GESTAO DA MUDANCA- 06. Coord. / Esp. ;ALAN RICIERI GIANOTTI-GESTÃO DA MUDANÇA-GESTÃO DA MUDANÇA
MARIANA LIMA ZAPAROLLI-COORDENADOR DE DHO- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-TREINAMENTO E DESENVOLVIMENTO
LUIZ FERNANDO RILLO OLIVEIRA-COORDENADOR DE COMUNICAÇÃO INTERNA E CLIMA-;DEBORA ETTORI DO PRADO ACERBI-DHO-COMUNICAÇÃO INTERNA
RAFAEL RODRIGUES DE ARAUJO-ESPECIALISTA EM REMUNERAÇÃO- 06. Coord. / Esp. ;KARINA MACHADO JARDIM-REMUNERAÇÃO-REMUNERAÇÃO
JESSICA KAKUITI RODRIGUES-ESPECIALISTA DE RELAÇÕES TRABALHISTAS- 06. Coord. / Esp. ;ELCINO ANTONIO BARBOSA-RELAÇÕES SINDICAIS-RELAÇÕES SINDICAIS
TAMIRES DA SILVA AMORIM-BUSINESS PARTNER DE RH- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-HRBP
FERNANDA OLIVEIRA DE ALMEIDA-BUSINESS PARTNER DE RH- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-HRBP
THAINA HARMEL WOSNIAK-BUSINESS PARTNER DE RH- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-HRBP
FÁBIO DO ESPIRITO SANTO CARNEIRO-ANL DE RECRUT E SELECAO PL- 08. Analista ;DEBORA ETTORI DO PRADO ACERBI-DHO-TALENT ACQUISITION
LARISSA LOPES DA SILVA-ANL RH PL- 08. Analista ;MARIANA LIMA ZAPAROLLI-DHO-TREINAMENTO E DESENVOLVIMENTO
DAIANE FERREIRA FUSQUINI-ANL ADM PESSOAL SR- 08. Analista ;ELCINO ANTONIO BARBOSA-RELAÇÕES SINDICAIS-RELAÇÕES SINDICAIS
ELLEN MÜTZEMBERG RAMBHAROSE.-ANL DE COMUNICACAO INTERNA PL- 08. Analista ;LUIZ FERNANDO RILLO OLIVEIRA-DHO-COMUNICAÇÃO INTERNA
ANA CAROLINA GUEZZI DE SOUZA-BUSINESS PARTNER DE RH- 06. Coord. / Esp. ;DEBORA ETTORI DO PRADO ACERBI-DHO-HRBP
TAÍS RODRIGUES CARREGA-ANL TREINAMENTO JR- 08. Analista ;MARIANA LIMA ZAPAROLLI-DHO-TREINAMENTO E DESENVOLVIMENTO
LEONARDO SENRA DE OLIVEIRA-ASSIST DE TREINAMENTO- 16. Assistente ;MARIANA LIMA ZAPAROLLI-DHO-TREINAMENTO E DESENVOLVIMENTO
IEDA APARECIDA DA SILVA-ASSIST COMUNIC INTERNA E CLIMA- 16. Assistente ;LUIZ FERNANDO RILLO OLIVEIRA-DHO-COMUNICAÇÃO INTERNA
RAIRA BERTIPAGLIA ALVES-ASSIST DE RECRUTAMENTO E SELECAO- 16. Assistente ;DEBORA ETTORI DO PRADO ACERBI-DHO-TALENT ACQUISITION
LETICIA ALBUQUERQUE DE SANTANA-ASSIST DE RECRUTAMENTO E SELECAO- 16. Assistente ;DEBORA ETTORI DO PRADO ACERBI-DHO-TALENT ACQUISITION
VADNA VAMILLE DE OLIVEIRA SANTIAGO-NUTRICIONISTA- 08. Analista ;DEBORA ACERBI-DHO-RESTAURANTE
JANAINA MARIA BATISTA-COZINHEIRA (O)- 13.Operação ;VADNA VAMILLE DE OLIVEIRA SANTIAGO-DHO-RESTAURANTE
MARIA DE FATIMA WANDERLEY DA SILVA-1/2 OF COZINHA- 13.Operação ;VADNA VAMILLE DE OLIVEIRA SANTIAGO-DHO-RESTAURANTE
CLAUDEILZA FATIMA CORREA GABRIEL-AUX DE COZINHA- 13.Operação ;VADNA VAMILLE DE OLIVEIRA SANTIAGO-DHO-RESTAURANTE
CLEUSA DIAS DO AMORIM-AUX DE COZINHA- 13.Operação ;VADNA VAMILLE DE OLIVEIRA SANTIAGO-DHO-RESTAURANTE

`;
      break;
    case "modelo4":
      conteudo = `
GAUTHAMA NASSIF FREIRE DE SOUZA-DIRETOR EXEC. MERCADO E INTELIGENCIA- 03. Diretor ;FABIO SANDRINI BAPTISTA-DIRETOR EXEC-DIRETOR EXEC
HENRIQUE MASSUELLA SALVADOR-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS GRANDES CONTAS
LORENNA IZABELLY MACIEL TARGINO DAMASCEN-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS
LUIS CARLOS DA SILVA-DIRETOR COMERCIAL- 03. Diretor ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS MANUT
LILIANA NUNES MELLO-GERENTE TECNICO SAUDE- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE
CRISTINA PARDUBSZKY-GER COMERCIAL- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-LICITAÇÃO E CONTRATOS PÚBLICOS
RENATO ROSSETO JUNIOR-GER TECNICO- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-ANÁLISE DE RISCO-ANÁLISE DE RISCO
HUAYNA ELOHIM PEREZ CONTRERAS-GER INTELIGENCIA DE MERCADO- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-INTELIGÊNCIA DE MERCADO-INTELIGÊNCIA DE MERCADO
DANIEL DE FREITAS SIQUEIRA-GERENTE DE DESENVOLVIMENTO E PLANEJAMENTO COMERCIAL- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO & DESENVOLVIMENTO
NATALIA CRISTINA DO CARMO GARCIA-GER COMUNICACAO E MARKETING- 05. Gerente ;GAUTHAMA NASSIF FREIRE DE SOUZA-MARKETING E CX-MARKETING E CX
MELINA DUARTE MARINI LOPES-GER COMERCIAL- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE
RAFAEL DE SIQUEIRA VELOSO-GER COMERCIAL- 05. Gerente ;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-VENDAS SAÚDE E MANUT
JULIANO TOGNOLI-GERENTE DE PRECIFICACAO E ADMINISTRACAO DE VENDAS-;GAUTHAMA NASSIF FREIRE DE SOUZA-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
FERNANDA ARCANJA DA MATA FORMIGARI-GER VENDAS- 05. Gerente ;HENRIQUE MASSUELLA SALVADOR-VENDAS-VENDAS GRANDES CONTAS
ARIANE CAMARGO REAL PRADO-GERENTE DE CONTAS-;GAUTHAMA NASSIF FREIRE DE SOUZA-VENDAS-VENDAS
CLAUDIA FERNANDES IGLESIAS-COORD TECNICO COMERCIAL-;LILIANA NUNES MELLO-VENDAS-VENDAS SAÚDE
RAIANE FAGUNDES MOURA-EXECUTIVO DE VENDAS SR- 09. Exec. Neg. ;HENRIQUE MASSUELLA SALVADOR-VENDAS-VENDAS GRANDES CONTAS
BRUNO VIDOLIN DE LIMA-PLANEJADOR SR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
ROGERIO REDIGOLO-PLANEJADOR SR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
MARCUS VINICIUS TEODORO SILVA-ANL DE PLANEJAMENTO SR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
LUIZ CELSO COELHO-ANL COMERCIAL PL- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
CRISTIANE YURI HISATUGO DEL DONO-ANL COMERCIAL SR- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
ALEXANDRE COSTA BATISTA-ANL COMERCIAL SR- 08. Analista ;CRISTINA PARDUBSZKY-VENDAS-LICITAÇÃO E CONTRATOS PÚBLICOS
MARCELO FORCHIN-ANL COMERCIAL SR- 08. Analista ;CRISTINA PARDUBSZKY-VENDAS-LICITAÇÃO E CONTRATOS PÚBLICOS
NICOLLE BARTOLASSI MARTINS DE OLIVEIRA-ANL DE COMUNICACAO E MARKETING SR-;NATALIA CRISTINA DO CARMO GARCIA-MARKETING E CX-MARKETING
ALFREDO MACIEL ALVES DOS SANTOS-ANL DE PLANEJAMENTO PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
CESAR WILLIANS PINHEIRO-ANALISTA DE PRECIFICACAO PL-;LORENNA IZABELLY MACIEL TARGINO DAMASCEN-VENDAS-PRECIFICAÇÃO
JULIO MARTINS NOGUEIRA-ANL INTEL MERCADO PL-;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-INTELIGÊNCIA DE MERCADO
JOYCE GENUINO DA SILVA-ANL DE DESENVOLVIMENTO PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-DESENVOLVIMENTO
GUSTAVO HENRIQUE PIMENTA BAZANELLI-ANL DE DESENVOLVIMENTO PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-DESENVOLVIMENTO
MARCELA HILLARY FONSECA DA SILVA-ANL COMERCIAL PL- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
JAMILE MONTEIRO RODRIGUES-ANL CUSTOMER SUCESS- 08. Analista ;NATALIA CRISTINA DO CARMO GARCIA-MARKETING E CX-CUSTOMER EXPERIENCE
MICHELLE ISRAELITA ROSA POVEDA-PLANEJADOR PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
VINICIUS TEBALDI MOREIRA-PLANEJADOR PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
JOSE APARECIDO DA SILVA JUNIOR-ANL DE PLANEJAMENTO PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
VAGNER FRANCISCO DE SOUZA-ANL RISCO DE SEGURANÇA PL- 08. Analista ;RENATO ROSSETO JUNIOR-ANÁLISE DE RISCO-ANÁLISE DE RISCO
GABRIEL DE AZEVEDO UECHI-ANL INTEL MERCADO PL-;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-INTELIGÊNCIA DE MERCADO
SERGIO VICTOR SANTOS DA SILVA-ANALISTA TÉCNICO JR- 08. Analista ;LILIANA NUNES MELLO-VENDAS-VENDAS SAÚDE
ALEX FABIANO EVANGELISTA-PLANEJADOR PL- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
CLEBER OLIVEIRA MELO-ANL DE DESENVOLVIMENTO JR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-DESENVOLVIMENTO
OSVALDO ALVES DA SILVA FILHO-ANL DE COMUNICACAO E MARKETING PL-;NATALIA CRISTINA DO CARMO GARCIA-MARKETING E CX-MARKETING
THAMIRES LUCAS DE OLIVEIRA-ANL COMERCIAL PL- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
DANIELLE JENNIFER LADARES DE ARAUJO-ANL COMERCIAL JR- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-ADMINISTRAÇÃO VENDAS
MICHEL SOUZA NUNES-PLANEJADOR JR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-PLANEJAMENTO
NICOLAS SOUSA CAVALCANTE DE JESUS-ANL COMERCIAL JR- 08. Analista ;CRISTINA PARDUBSZKY-VENDAS-LICITAÇÃO E CONTRATOS PÚBLICOS
DIEGO DA SILVA RIBEIRO-ANL COMERCIAL JR- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-ADMINISTRAÇÃO VENDAS
JOÃO PEDRO PEREIRA RODRIGUES DE SOUZA-ANL DE DESENVOLVIMENTO JR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-DESENVOLVIMENTO
KETHELYN DANTAS DOS SANTOS-ANL COMERCIAL JR- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
LUCAS VELLA SANCHES-ANL COMERCIAL JR- 08. Analista ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
ISABELLA DOS REIS COSTA-ANL DE DESENVOLVIMENTO JR- 08. Analista ;DANIEL DE FREITAS SIQUEIRA-PLANEJAMENTO & DESENVOLVIMENTO-DESENVOLVIMENTO
VICTOR LIMA DA COSTA-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
FERNANDA CRISTINE DA SILVA MACHADO-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
NATHAN CESAR RODRIGUES DA SILVA-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
VITOR HENRIQUE PEREIRA DE SOUZA SILVA-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
GABRIEL ERNESTO HOFMANN-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
WELLINGTON RODRIGUES DE FREITAS-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
KASSIA JULIANY MEDEIROS DOS SANTOS-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
CELIA REGINA OGEDA FEITOSA-ANL COMERCIAL JR- 08. Analista ;HUAYNA ELOHIM PEREZ CONTRERAS-INTELIGÊNCIA DE MERCADO-IS
ANA KAROLINE DA SILVA -ASSIST COMERCIAL- 16. Assistente ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-PRECIFICAÇÃO
HELOISA LOPES SILVA-AUX ADMINISTRATIVO- 17. Auxiliar ;JULIANO TOGNOLI-ADMINISTRAÇÃO VENDAS-ADMINISTRAÇÃO VENDAS

`;
      break;
    case "modelo5":
      conteudo = `
MARAISA ALBERTINI GOMES-GER GERAL AUD INTERNA E COMPLIANCE- 04. Gerente Sr ;FABIO SANDRINI BAPTISTA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
SORAYA DOS SANTOS DE ALMEIDA-COORD GOVERNANÇA RISCOS E COMP- 06. Coord. / Esp. ;MARAISA ALBERTINI GOMES-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
ROSEMEIRE CRUZ DE SOUZA-AUDITOR INTERNO PL- 13.Operação ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-AUDITORIA INTERNA
JULIA MARINS BUOSI-AUDITOR INTERNO PL- 13.Operação ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-AUDITORIA INTERNA
PRISCILA DUARTE FERNANDES ROSALEN-AUDITOR INTERNO PL- 13.Operação ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-SISTEMA DE GESTÃO INTEGRADO
ELCE RODRIGUES DOS SANTOS-ANL ASSUNTOS LEGAIS SR- 08. Analista ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA - SOCIETÁRIO/REGULATÓRIO
TASSIA SARDINHA ROCHA-ANL ASSUNTOS LEGAIS PL- 08. Analista ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA - SOCIETÁRIO/REGULATÓRIO
DENISE FERNANDA CAVALINI BONADIO KOSCHNI-ANL DE GOVERNANÇA CORP PL- 08. Analista ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA - SOCIETÁRIO/REGULATÓRIO
MARCELA SORNOQUI SANTIAGO-ANALISTA DE COMPLIANCE JR- 08. Analista ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-COMPLIANCE
MAYARA TEIXEIRA MAIA DA SILVA-ASSIST ADMINISTRATIVO- 16. Assistente ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-AUDITORIA INTERNA
THIAGO SANTANA DOS SANTOS SILVA-ASSIST ADMINISTRATIVO- 16. Assistente ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA - SOCIETÁRIO/REGULATÓRIO
SARAH CRISTINA DE SOUSA CARVALHO-AUX ADMINISTRATIVO- 17. Auxiliar ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA, RISCOS E COMPLIANCE
VITOR DUELA MANSOUR-AUX ADMINISTRATIVO- 17. Auxiliar ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-GOVERNANÇA - SOCIETÁRIO/REGULATÓRIO
VINICIUS DE MORAIS BUBLITZ-ANL DA QUALIDADE JR- 08. Analista ;SORAYA DOS SANTOS DE ALMEIDA-GOVERNANÇA, RISCOS E COMPLIANCE-SISTEMA DE GESTÃO INTEGRADO

`;
      break;
    case "modelo6":
      conteudo = `
ANTONIO CAVALCANTI JUNIOR-CFO- 02. VP ;FABIO SANDRINI BAPTISTA-FINANCEIRO-FINANCEIRO
ADRIANA CORROCHANO MORI-DIRETOR(A) JURIDICO-03. Diretor ;ANTONIO CAVALCANTI JUNIOR-JURÍDICO-JURÍDICO
MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-DIRETOR CONTABIL E FISCAL-03. Diretor ;ANTONIO CAVALCANTI JUNIOR-CONTÁBIL E FISCAL-CONTÁBIL E FISCAL
CLODOVIRGES NEVES DE AMORIM JUNIOR-DIRETOR DE CONTROLADORIA- 03. Diretor ;ANTONIO CAVALCANTI JUNIOR-CONTROLADORIA-CONTROLADORIA
GUSTAVO HELLMEISTER BELLORIO-GER SR PROCESSOS E INTEGRAÇÕES- 04. Gerente Sr ;ANTONIO CAVALCANTI JUNIOR-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
WALDENIR LEONEL GIACONTO-GER FINANCEIRO- 05. Gerente ;ANTONIO CAVALCANTI JUNIOR-FINANCEIRO-FINANCEIRO
TALITA DE OLIVEIRA RODRIGUES CASTANHO-GER JURIDICO DE CONTRATOS- 05. Gerente ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO CONTRATO
DIEGO COUREL MONTANARI-GER FISCAL- 05. Gerente ;MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-CONTÁBIL E FISCAL-FISCAL
RICARDO CÉSAR DE OLIVEIRA FERREIRA-GER DE CONTROLADORIA- 05. Gerente ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA-CONTROLADORIA
THAIS DANIELLI GIMENEZ-GER JURIDICO- 05. Gerente ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO CONTENCIOSO
RICARDO FERREIRA DOS SANTOS-COORD DE PROJETOS- 06. Coord. / Esp. ;GUSTAVO HELLMEISTER BELLORIO-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
CAROLINE DOMINGUES ORTOLANI-COORD DE FATURAMENTO - 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA-GARANTIA DA RECEITA
VICTOR HUGO DE OLIVEIRA BATISTA-COORD FINANCEIRO- 06. Coord. / Esp. ;WALDENIR LEONEL GIACONTO-FINANCEIRO-FINANCEIRO
DENNIS SILVESTRIM DE FREITAS-COORD CONTABIL- 06. Coord. / Esp. ;MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-CONTÁBIL E FISCAL-CONTABIL
JOSE RICARDO MARTINS-COORDENADOR PREVIDENCIÁRIO- 06. Coord. / Esp. ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-PREVIDENCIÁRIO
GILMAR DA SILVA SANTANA-ESPECIALISTA CONTABIL- 06. Coord. / Esp. ;MAGNUS MONTEIRO DE OLIVEIRA JUNIOR-CONTÁBIL E FISCAL-CONTABIL
DANIELLE MARCINATTO FRANÇA-ESPECIALISTA FISCAL- 06. Coord. / Esp. ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
DEBORA EVELIN SANCHEZ-ESPECIALISTA FISCAL- 06. Coord. / Esp. ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
CAROLINA BENEDETTI PAGANINI-ESPECIALISTA PREVIDENCIARIO- 06. Coord. / Esp. ;JOSE RICARDO MARTINS-CONTÁBIL E FISCAL-PREVIDENCIÁRIO
TAYNAH ARAUJO DOS SANTOS-ADVOGADO SR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
CAIO AUGUSTO SATURNO-ADVOGADO SR- 08. Analista ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO TRIBUTÁRIO
THAIZA NOVOA TEIXEIRA-ADVOGADO CONTRATOS SR- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
THAMIRES JURADO CHIARELLI-ADVOGADO CONTRATOS PL- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
JESSICA CASTRO DE PAULA-ADVOGADO PL- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
FELIPE HENRIQUE MUNHOZ PAVANELLI-ADVOGADO CONTRATOS PL- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
JESSICA REGINA OLIVEIRA LAMBAK-ADVOGADO CONTRATOS PL- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
RENAN FORCETTO FELIPE-ADVOGADO CONTRATOS PL- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
ANA CAROLINA BERNARDO VIEIRA PEREZ-ADVOGADO JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
NATHALIA VANZELLI DA COSTA-ADVOGADO JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
IVERSON LIMA DE SOUZA-ADVOGADO JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
PEDRO EDUARDO DA SILVA NAVAS-ADVOGADO JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
LUIZ GUSTAVO OLIVEIRA DE SOUZA-ADVOGADO JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
VITOR POGGIATO CAVALCANTE-ADVOGADO JR- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
NATASHY BUENO VESSONI-ADVOGADO JR- 08. Analista ;TALITA DE OLIVEIRA RODRIGUES CASTANHO-JURÍDICO-JURÍDICO CONTRATO
EURICO FERNANDES SEVERINO-ANALISTA DE PROJETOS SR- 08. Analista ;RICARDO FERREIRA DOS SANTOS-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
RAQUEL DE AVEIRO DOMINGUES-ANL CONTABIL SR- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
MICHEL AGRESTA BARREIROS-ANL CONTABIL SR- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
VINICIUS GUEDES INOUE-ANALISTA DE PROJETOS SR- 08. Analista ;RICARDO FERREIRA DOS SANTOS-ESCRITÓRIO PROJETOS-ESCRITÓRIO PROJETOS
GILMARA ASSUNCAO DE OLIVEIRA-ANL CONTABIL SR- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
CAIO PEREIRA DE MORAES NUNES-ANL FINANCEIRO SR- 08. Analista ;VICTOR HUGO DE OLIVEIRA BATISTA-FINANCEIRO-CONTAS A RECEBER
FERNANDA SILVA GARRO-ANL FINANCEIRO SR- 08. Analista ;WALDENIR LEONEL GIACONTO-FINANCEIRO-TESOURARIA
MARILUA ROMERO MANZALLI-ANL FINANCEIRO SR- 08. Analista ;WALDENIR LEONEL GIACONTO-FINANCEIRO-CONTAS A PAGAR
DIANGELIS DE ALMEIDA GUIMARAES FRITZ-ANL INDICADORES PL- 08. Analista ;ADRIANA CORROCHANO MORI-JURÍDICO-JURÍDICO CONTENCIOSO
HELIO NASCIMENTO DOS SANTOS-ANL CONTABIL SR- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
TATIANA FERREIRA MORAES-ANL FISCAL SR- 08. Analista ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
MARIA APARECIDA DA SILVA-ANL FINANCEIRO PL- 08. Analista ;CAROLINE DOMINGUES ORTOLANI-CONTROLADORIA-GARANTIA DA RECEITA
JESSICA APARECIDA ALVES DE SOUZA PROCOPI-ANL FINANCEIRO PL- 08. Analista ;WALDENIR LEONEL GIACONTO-FINANCEIRO-TESOURARIA
BRUNO MONTEIRO NEGRI-ANL FISCAL PL- 08. Analista ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
SIBELI REGINA DE ALMEIDA-ANL FISCAL PL- 08. Analista ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
DIANA AMARAL DA FONSECA-ANL FISCAL PL- 08. Analista ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
WALDEMIR DA SILVA-ANL CONTABIL PL- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
MARISELMA NUNES GREGORIO-ANL CONTABIL PL- 08. Analista ;DENNIS SILVESTRIM DE FREITAS-CONTÁBIL E FISCAL-CONTABIL
NICOLE NAVARRO MARTINS-ANL FINANCEIRO PL- 08. Analista ;WALDENIR LEONEL GIACONTO-FINANCEIRO-CONTAS A PAGAR
THAYS DE SOUZA GIMENEZ DOS SANTOS-ANL ADM PESSOAL JR- 08. Analista ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
JONATAS DA SILVA ESPINDOLA-ANL FINANCEIRO JR- 08. Analista ;CAROLINE DOMINGUES ORTOLANI-CONTROLADORIA-GARANTIA DA RECEITA
CLARISSA DOMENICA SILVEIRA-ASSIST JURIDICO- 16. Assistente ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
KELI CRISTINA FERNANDES DANTAS-ASSIST DE CREDITO E COBRANCA- 16. Assistente ;VICTOR HUGO DE OLIVEIRA BATISTA-FINANCEIRO-CRÉDITO E COBRANÇA
DAIANE CRISTINA DE SOUZA-ASSIST DE CREDITO E COBRANCA- 16. Assistente ;VICTOR HUGO DE OLIVEIRA BATISTA-FINANCEIRO-CRÉDITO E COBRANÇA
IVANEIDE DE SANTANA SANTOS-ASSIST ADMINISTRATIVO- 16. Assistente ;VICTOR HUGO DE OLIVEIRA BATISTA-FINANCEIRO-CONTAS A RECEBER
JOÃO VITOR RIBEIRO DE LIMA-ASSIST JURIDICO- 16. Assistente ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
DANUBIA DOS SANTOS MAIA-ASSIST ADMINISTRATIVO- 16. Assistente ;CAROLINE DOMINGUES ORTOLANI-CONTROLADORIA-GARANTIA DA RECEITA
TAWANE NUNES SILVA-ASSIST FINANCEIRO- 16. Assistente ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL
CLEVERSON DA SILVA XAVIER-AUX ADMINISTRATIVO- 17. Auxiliar ;THAIS DANIELLI GIMENEZ-JURÍDICO-JURÍDICO CONTENCIOSO
YURI ANJOS DOS SANTOS-AUX FISCAL- 17. Auxiliar ;DIEGO COUREL MONTANARI-CONTÁBIL E FISCAL-FISCAL

`;
      break;
    case "modelo7":
      conteudo = `
FABIO PANHONI DE PAULA PEREIRA-DIRETOR M&A- 02. VP ;FABIO SANDRINI BAPTISTA-M&A-M&A
LUIZ HENRIQUE RAMOS FERRAZ-GERENTE DE M&A- 05. Gerente ;FABIO PANHONI DE PAULA PEREIRA-M&A-M&A
OSVALDO LUCIANO DO AMARAL JÚNIOR-COORD M&A- 06. Coord. / Esp. ;LUIZ HENRIQUE RAMOS FERRAZ-M&A-M&A
THIERRY TOKOH BLONDEAU-ANL M&A SR- 08. Analista ;OSVALDO LUCIANO DO AMARAL JÚNIOR-M&A-M&A
MARCOS VINICIUS BARROSO ARAUJO-ANL M&A JR-;OSVALDO LUCIANO DO AMARAL JÚNIOR-M&A-M&A

`;
      break;
    case "modelo8":
      conteudo = `
DENILSON MARCIO RODRIGUES-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;MARCOS ROBERTO MORETTI DE ALMEIDA-OPERAÇÕES-OPERAÇÕES
CLAUDIA ALVES DOS SANTOS-GER COMERCIAL REGIONAL- 05. Gerente ;DENILSON MARCIO RODRIGUES-COMERCIAL-COMERCIAL
SIDNEI FRANCISCO INOCENCIO-GER NEGOCIOS- 05. Gerente ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-OPERAÇÕES
MARTA SERPA DE FARIAS-GER CONTRATO- 05. Gerente ;SIDNEI FRANCISCO INOCENCIO-OPERAÇÕES-CLIENTE
SIMONI DE SOUZA VIEIRA-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-CONTROLADORIA/FINANÇAS-CONTROLADORIA
GUSTAVO FERNANDO DE SOUZA BENTO-COORD OPERACIONAL- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-OPERAÇÕES
TIAGO BRITO DA SILVA-COORDENADOR (A)- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-OPERAÇÕES
ROBSON RODRIGUES ROCHA-COORDENADOR (A)- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-CLIENTE
RUDINEI DA SILVA NOBRE-COORDENADOR (A)- 06. Coord. / Esp. ;TIAGO BRITO DA SILVA-OPERAÇÕES-CLIENTE
CHARLES MACARIO DOS SANTOS FILHO-COORDENADOR (A)- 06. Coord. / Esp. ;DENILSON MARCIO RODRIGUES-OPERAÇÕES-OPERAÇÕES
EVERTON DE LIMA HOFFMANN-COORD OPERACIONAL- 06. Coord. / Esp. ;SIDNEI FRANCISCO INOCENCIO-OPERAÇÕES-OPERAÇÕES
WASHINGTON GONCALVES MOREIRA-COORD OPERACIONAL- 06. Coord. / Esp. ;SIDNEI FRANCISCO INOCENCIO-OPERAÇÕES-OPERAÇÕES
MARIA FERNANDA CARDOSO GIBSON-TEC SEG DO TRABALHO- 10. Técnico ;CHARLES MACARIO DOS SANTOS FILHO-OPERAÇÕES-CLIENTE
JULIANA RAMOS-TECNICO MEIO AMBIENTE - 10. Técnico ;TIAGO BRITO DA SILVA-OPERAÇÕES-CLIENTE
ISAQUE PROCOPIO DE BRITO-TEC SEG DO TRABALHO- 10. Técnico ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
DENISE AMARAL FERNANDES-TEC SEG DO TRABALHO- 10. Técnico ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
ELIEZER JOSÉ ZACARIAS-TEC SEG DO TRABALHO- 10. Técnico ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
NATANAEL TAVARES CEZAR-EXECUTIVO DE VENDAS SR- 09. Exec. Neg. ;CLAUDIA ALVES DOS SANTOS-COMERCIAL-VENDAS
DIOGO COSTA E SILVA-EXECUTIVO DE VENDAS SR- 09. Exec. Neg. ;CLAUDIA ALVES DOS SANTOS-COMERCIAL-VENDAS
ANDRE ROSA FIGUEIREDO-EXECUTIVO DE VENDAS SR- 09. Exec. Neg. ;CLAUDIA ALVES DOS SANTOS-COMERCIAL-VENDAS
ALINE CHRISTINE BARBOSA-ANL COMERCIAL PL- 08. Analista ;CLAUDIA ALVES DOS SANTOS-COMERCIAL-PRECIFICAÇÃO
YURI GONCALVES MARCELO-ANL CONTROLADORIA JR- 08. Analista ;SIMONI DE SOUZA VIEIRA-CONTROLADORIA/FINANÇAS-CONTROLADORIA
GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-ANL ADM PESSOAL JR- 08. Analista ;DENILSON MARCIO RODRIGUES-RECURSOS HUMANOS-RECURSOS HUMANOS
GEOVANA DA SILVA DOS SANTOS DALMAZ-ANL ADMINISTRATIVO JR- 08. Analista ;ROBSON RODRIGUES ROCHA-OPERAÇÕES-CLIENTE
SUELEN CRISTINA DE JESUS-ANL DE RECRUT E SELECAO JR- 08. Analista ;GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-RECURSOS HUMANOS-R&S
KEYLA LEAL DOS REIS-ANL DE RECRUT E SELECAO JR- 08. Analista ;GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-RECURSOS HUMANOS-R&S
FRANCINE CAMILE DOS SANTOS-ANALISTA OPERACIONAL- 08. Analista ;EVERTON DE LIMA HOFFMANN-OPERAÇÕES-CLIENTE
CAMILA CRISTINA CAMARGO-ANL COMERCIAL JR- 08. Analista ;CLAUDIA ALVES DOS SANTOS-COMERCIAL-PRECIFICAÇÃO
ANDREW GABRIEL DE OLIVEIRA SILVA-ASSIST ADMINISTRATIVO- 16. Assistente ;SIMONI DE SOUZA VIEIRA-APOIO OPERACIONAL-COMPRAS
ELEDIR KOPPLIN DE LIMA-ASSIST ADMINISTRATIVO- 16. Assistente ;TIAGO BRITO DA SILVA-APOIO OPERACIONAL-FOPAG+BENEFÍCIOS+DESLIGAMENTO+DOCUMENTAÇÃO
ELIESER FERREIRA DA SILVA JUNIOR-ASSIST RH- 16. Assistente ;GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-RECURSOS HUMANOS-FOPAG+BENEFÍCIOS+DESLIGAMENTO+DOCUMENTAÇÃO
DALVANA MARIA PEDROSO-ASSIST ADMINISTRATIVO- 16. Assistente ;SIMONI DE SOUZA VIEIRA-APOIO OPERACIONAL-FATURAMENTO
FRANCIELLY ROSA DE OLIVEIRA RODES ALVES-ASSIST ADMINISTRATIVO- 16. Assistente ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
DHIEINISE KIMBERLI SANTOS-ASSIST ADMINISTRATIVO- 16. Assistente ;GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-RECURSOS HUMANOS-R&S
ANA FRANCIELE SACRAMENTO BRANDAO-ASSIST ADMINISTRATIVO- 16. Assistente ;CHARLES MACARIO DOS SANTOS FILHO-APOIO OPERACIONAL-FOPAG+BENEFÍCIOS+DESLIGAMENTO+DOCUMENTAÇÃO
PAULO RENATO ROQUE DA CRUZ-ASSIST ADMINISTRATIVO- 16. Assistente ;TIAGO BRITO DA SILVA-OPERAÇÕES-CLIENTE
ANNY CHYRLLY FERREIRA DE ALMEIDA -ASSIST ADMINISTRATIVO- 16. Assistente ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
MARIA LUCIA DA SILVA-ASSIST ADMINISTRATIVO- 16. Assistente ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
ERICK KRISTHIAN WEISSENBERG GARCIA-ASSIST ADMINISTRATIVO- 16. Assistente ;MARTA SERPA DE FARIAS-OPERAÇÕES-CLIENTE
RENATA FRANCO CZARNIK-ASSIST ADMINISTRATIVO- 16. Assistente ;CHARLES MACARIO DOS SANTOS FILHO-OPERAÇÕES-CLIENTE
KESSIA SILVA NAHON-ASSIST ADM DE PESSOAL- 16. Assistente ;GILSIMARA NAVARRO DE ANDRADE DO NASCIMEN-RECURSOS HUMANOS-DESLIGAMENTO

`;
      break;
    case "modelo9":
      conteudo = `
    RENATO ROVELO-GER DE SESMT- 05. Gerente ;MARISSANDRA LOEFF-SESMT-SESMT
FILIPE VILLALVA BARBOSA-MEDICO DO TRABALHO - COORDENADOR- 06. Coord. / Esp. ;RENATO ROVELO-SESMT-MEDICINA DO TRABALHO
JOSE DE SOUZA MAIA FILHO-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
DANIELI APARECIDA ASSAF LEMES-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
MAURO TADEU FAXINA-MEDICO DO TRABALHO- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
FILIPE VILLALVA BARBOSA-MEDICO DO TRABALHO- 08. Analista ;RENATO ROVELO-SESMT-MEDICINA DO TRABALHO
MARCOS PACINI-ENG SEG TRABALHO PL- 08. Analista ;RENATO ROVELO-SESMT-SEGURANÇA DO TRABALHO
KATIA REGINA REDONDO-FONOAUDIOLOGO (A)- 08. Analista ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
MIRIAM MARI MARTINHO FERRADOR-ENFERMEIRA (O) DO TRABALHO- 10. Técnico ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
MONIQUE BRITO SANTANA-ENFERMEIRA (O) DO TRABALHO- 10. Técnico ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
ADRIANA MONACI DOS SANTOS MARTINS-ENFERMEIRA (O) DO TRABALHO- 10. Técnico ;FILIPE VILLALVA BARBOSA-SESMT-MEDICINA DO TRABALHO
ANDREIA DA CRUZ-ENG SEG TRABALHO PL- 08. Analista ;RENATO ROVELO-SESMT-SEGURANÇA DO TRABALHO
ANDREIA DA CRUZ-ENG SEG TRABALHO PL- 08. Analista ;RENATO ROVELO-SESMT-SEGURANÇA DO TRABALHO
FERNANDO WILIAM RAMELLO-ENG SEG TRABALHO JR- 08. Analista ;RENATO ROVELO-SESMT-SEGURANÇA DO TRABALHO
FERNANDO WILIAM RAMELLO-ENG SEG TRABALHO JR- 08. Analista ;RENATO ROVELO-SESMT-SEGURANÇA DO TRABALHO
DOUGLAS PUCINELI ALVES-TEC SEG DO TRABALHO- 10. Técnico ;FERNANDO WILIAM RAMELLO-SESMT-SEGURANÇA DO TRABALHO
ANA CLEIDE DA SILVA LEAL-TEC SEG DO TRABALHO II- 10. Técnico ;FERNANDO WILIAM RAMELLO-SESMT-SEGURANÇA DO TRABALHO
MURILO PUCINELI ALVES-TEC SEG DO TRABALHO II- 10. Técnico ;FERNANDO WILIAM RAMELLO-SESMT-SEGURANÇA DO TRABALHO
SIDNEY RODRIGUES-TEC SEG DO TRABALHO- 10. Técnico ;FERNANDO WILIAM RAMELLO-SESMT-SEGURANÇA DO TRABALHO
RAFAELA APARECIDA MARQUES DA SILVA -ASSIST ADMINISTRATIVO- 16. Assistente ;MONIQUE BRITO SANTANA-SESMT-MEDICINA DO TRABALHO
BRUNA MARCELLE FREITAS BARBOSA-ASSIST ADMINISTRATIVO- 16. Assistente ;ADRIANA MONACI DOS SANTOS MARTINS-SESMT-MEDICINA DO TRABALHO
MARIA LUIZA ANDRADE DE MORAES-ASSIST ADMINISTRATIVO- 16. Assistente ;ADRIANA MONACI DOS SANTOS MARTINS-SESMT-MEDICINA DO TRABALHO
THAIS HELENA HENRIQUE-AUX DE ENFERMAGEM DO TRABALHO- 10. Técnico ;ADRIANA MONACI DOS SANTOS MARTINS-SESMT-MEDICINA DO TRABALHO
LUZINEIDE SOARES MOREIRA DA SILVA-AUX DE ENFERMAGEM DO TRABALHO- 10. Técnico ;MIRIAM MARI MARTINHO FERRADOR-SESMT-MEDICINA DO TRABALHO
MARIA VICENTINA PAIVA RIBEIRO-AUX DE ENFERMAGEM DO TRABALHO- 10. Técnico ;MIRIAM MARI MARTINHO FERRADOR-SESMT-MEDICINA DO TRABALHO
SUSANE CRISTINA TIAGO -AUX ADMINISTRATIVO- 17. Auxiliar ;MONIQUE BRITO SANTANA-SESMT-MEDICINA DO TRABALHO
GEOVANNA DA SILVA NICACIO-AUX ADMINISTRATIVO- 17. Auxiliar ;MONIQUE BRITO SANTANA-SESMT-MEDICINA DO TRABALHO
`;
      break;
    case "modelo10":
      conteudo = `
HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-DIRETOR EXECUTIVO DE OPERAÇÕES- 03. Diretor ;CESAR LEONEL DA SILVA NETO-OPERAÇÕES-OPERAÇÕES
JOSE AQUILES FERREIRA DA SILVA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
DANIELLY LIMA DA SILVA BRAGA-GER RECURSOS HUMANOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-RECURSOS HUMANOS-RECURSOS HUMANOS
FERNANDA FELIX ALVES BARROS-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
FERNANDA FELIX ALVES BARROS-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
DJANINE RODRIGUES DE SANTANA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
FRED EDUARDO CASTANHA BARRETO TENORIO-GER COMERCIAL REGIONAL- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-COMERCIAL-VENDAS
EVERTON GUILHERME UCHOA RODRIGUES-GER CONTRATO- 05. Gerente ;DJANINE RODRIGUES DE SANTANA-OPERAÇÕES-CLIENTE
DIEGO PRADO MESQUITA VIANA-GER NEGOCIOS- 05. Gerente ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-OPERAÇÕES-OPERAÇÕES
MONIQUE CIBELLE SANTOS DA SILVA-GERENTE DE CONTAS-;FRED EDUARDO CASTANHA BARRETO TENORIO-COMERCIAL-VENDAS
ROGERIA FERREIRA BELARMINO -GERENTE- 05. Gerente ;SHARA INGRID DE SOUSA-OPERAÇÕES-CLIENTE
SHIRLEY PEREIRA DE MATTOS-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;HEBERTY EMMANOEL DE AGUIAR R BRASILEIRO-CONTROLADORIA/FINANÇAS-CONTROLADORIA
FIDES CHAVES ALVES DA SILVA-MEDICO DO TRABALHO- 08. Analista ;VALDENEI FRANCA-OPERAÇÕES-CLIENTE
VALDENEI FRANCA-COORD OPERACIONAL- 06. Coord. / Esp. ;JOSE AQUILES FERREIRA DA SILVA-OPERAÇÕES-OPERAÇÕES
JUNIOR GONCALVES DA ROSA-COORD OPERACIONAL- 06. Coord. / Esp. ;JOSE AQUILES FERREIRA DA SILVA-OPERAÇÕES-OPERAÇÕES
VALTON BRANDAO DE ANDRADE-COORD OPERACIONAL- 06. Coord. / Esp. ;FERNANDA FELIX ALVES BARROS-OPERAÇÕES-OPERAÇÕES
LUCAS RIBEIRO DE PAULA -COORDENADOR (A)- 06. Coord. / Esp. ;LUCAS RIBEIRO DE PAULA-OPERAÇÕES-CLIENTE
FELIPE DE OLIVEIRA BENIGNO -COORDENADOR (A)- 06. Coord. / Esp. ;DJANINE RODRIGUES DE SANTANA-OPERAÇÕES-OPERAÇÕES
CARLOS WAGNER DE SOUZA SANTOS-COORD OPERACIONAL- 06. Coord. / Esp. ;DIEGO PRADO MESQUITA VIANA-OPERAÇÕES-OPERAÇÕES
GLEYDSON SILVA DE LIRA-COORD OPERACIONAL- 06. Coord. / Esp. ;JOSE AQUILES FERREIRA DA SILVA-OPERAÇÕES-OPERAÇÕES
ADERVAL COELHO DE MACEDO-MEDICO DO TRABALHO- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-MEDICINA DO TRABALHO
GICELIO FERREIRA DE ANDRADE-COORD(A) DE CONTRATO- 06. Coord. / Esp. ;JOSE AQUILES FERREIRA DA SILVA-OPERAÇÕES-CLIENTE
JOSE ADRIANO DA SILVA-COORD OPERACIONAL- 06. Coord. / Esp. ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-APOIO JURÍDICO
TAIS LIDIANE SANTOS RODRIGUES-ENG SEG TRABALHO- 08. Analista ;VALDENEI FRANCA-OPERAÇÕES-CLIENTE
RICARDO MEDEIROS DE AQUINO-ENG SEG TRABALHO JR- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-SEGURANÇA DO TRABALHO
EDUARDO SANTOS DA NOBREGA-TEC SEG DO TRABALHO PL- 10. Técnico ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-SEGURANÇA DO TRABALHO
URSOLA DE LIMA VARGAS-TEC ENFERMAGEM DO TRABALHO- 10. Técnico ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-MEDICINA DO TRABALHO
PAULO FRANCISCO DE LUNA NETO-TEC SEG DO TRABALHO PL- 10. Técnico ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-SEGURANÇA DO TRABALHO
JOADLER FERREIRA ALVES DE SOUZA-TEC SEG DO TRABALHO PL- 10. Técnico ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-SEGURANÇA DO TRABALHO
REJANY GONDIM SANTOS-TEC SEG DO TRABALHO- 10. Técnico ;VALDENEI FRANCA-OPERAÇÕES-CLIENTE
FABRICIA FERNANDA ANDRADE PRATA-TEC SEG DO TRABALHO- 10. Técnico ;VALDENEI FRANCA-OPERAÇÕES-CLIENTE
STELA DE NARDI DA SILVA -ANL RISCO SR- 08. Analista ;DANIELE DE ANDRADE BISPO SANTOS-OPERAÇÕES-CLIENTE
MARIA ROMENIA AZEVEDO CRUZ DE MATOS-EXECUTIVO DE VENDAS PL- 09. Exec. Neg. ;FRED EDUARDO CASTANHA BARRETO TENORIO-COMERCIAL-VENDAS
CLEYTSON THIAGO CAMPOS LIMA-ANL RISCO SR- 08. Analista ;FERNANDA FELIX ALVES BARROS-APOIO OPERACIONAL-ANÁLISE DE RISCO
MARIA DO SOCORRO SALGUEIRO ACIOLI SILVEI-ANL DE CONTROLADORIA PL- 08. Analista ;SHIRLEY PEREIRA DE MATTOS-CONTROLADORIA/FINANÇAS-CONTROLADORIA
SANDRA BARROS GONCALVES-ANL RH PL- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-DHO (R&S +T&D+ Clima + RH em Campo +Apoio a Eventos+Integração)
DIEGO D ANGELLES SILVA DE SOUZA-ANL DE OPERACOES- 08. Analista ;FERNANDA FELIX ALVES BARROS-APOIO OPERACIONAL-FATURAMENTO
RICARDO BATISTA LIMA DA SILVA-ANL ADM PESSOAL PL- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-FOPAG + INDICADORES + CHAMADOS+ ADMISSÃO
VERHUSKA SILVA DE SOUSA-ANL DE OPERACOES- 08. Analista ;FERNANDA FELIX ALVES BARROS-APOIO OPERACIONAL-Gestão de contratos
GRAZIELLE DA CUNHA GONCALVES-ANL DE OPERACOES- 08. Analista ;JOSE AQUILES FERREIRA DA SILVA-APOIO OPERACIONAL-FATURAMENTO
MONICA LUCIA CABRAL DA SILVA-ANL DE OPERACOES- 08. Analista ;DJANINE RODRIGUES DE SANTANA-APOIO OPERACIONAL-Gestão de contratos
AMANDA PAULINO DE SOUZA-ANL DE OPERACOES- 08. Analista ;DIEGO PRADO MESQUITA VIANA-APOIO OPERACIONAL-Gestão de contratos
MOISES LUNA DE SANTANA-ANL DE OPERACOES- 08. Analista ;DJANINE RODRIGUES DE SANTANA-APOIO OPERACIONAL-FATURAMENTO
 MICHELINE MARIA DA CONCEICAO FRANCA GON-ANL DE OPERACOES- 08. Analista ;JOSE AQUILES FERREIRA DA SILVA-APOIO OPERACIONAL-Gestão de contratos
SUCILY BARBOZA DE LUCENA-ANL ADM PESSOAL JR- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-MACRO PROC FOLHA
CRISTIANE GALINDO DALTO BAY-ANL ADM PESSOAL JR- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-FOPAG+BENEFÍCIOS+admissão
VERONICA MARIA DOS SANTOS SOARES-ANL DE OPERACOES- 08. Analista ;FERNANDA FELIX ALVES BARROS-APOIO OPERACIONAL-Suporte Operacional: Controle de Material e equipamentos, Nexti, reciclagem, atendimento aos colaboradores.
MARAYZA GONCALVES DA SILVA-ANL COMERCIAL JR- 08. Analista ;FRED EDUARDO CASTANHA BARRETO TENORIO-COMERCIAL-PRECIFICAÇÃO
AMANDA BARBARA RODRIGUES COSTA-ANL RH JR- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-DHO (R&S +T&D+ Clima + RH em Campo +Apoio a Eventos+Integração)
JOAO VICTOR CORDEIRO DA SILVA-ANL RH JR- 08. Analista ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-DHO (R&S +T&D+ Clima + RH em Campo +Apoio a Eventos+Integração)
SHEILA PEREIRA DE OLIVEIRA LEAL-ANL FINANCEIRO JR- 08. Analista ;SHIRLEY PEREIRA DE MATTOS-FINANCEIRO-FINANCEIRO
BETANIA LUCIA XAVIER DE ALBUQUERQUE-ANL DE OPERACOES- 08. Analista ;DJANINE RODRIGUES DE SANTANA-APOIO OPERACIONAL-DOCUMENTAÇÃO
RAYSSA LOPES ALVES-ANL DE OPERACOES- 08. Analista ;LUCAS RIBEIRO DE PAULA-OPERAÇÕES-CLIENTE
GEAN CAVALCANTI DA SILVA -ASSIST ADMINISTRATIVO- 16. Assistente ;SHIRLEY PEREIRA DE MATTOS-CONTROLADORIA/FINANÇAS-FROTAS
JOSE WILTON MARTINS-ASSIST ADMINISTRATIVO- 16. Assistente ;SHIRLEY PEREIRA DE MATTOS-CONTROLADORIA/FINANÇAS-FROTAS
JESSICA RAYANE GOMES FERREIRA-ASSIST ADMINISTRATIVO- 16. Assistente ;SHIRLEY PEREIRA DE MATTOS-CONTROLADORIA/FINANÇAS-FINANCEIRO
LUCIANA MARIA DA ROCHA SILVA-ASSIST ADMINISTRATIVO- 16. Assistente ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-DOCUMENTAÇÃO
AILSON XAVIER DE SOUZA-ASSIST ADMINISTRATIVO- 16. Assistente ;SHIRLEY PEREIRA DE MATTOS-CONTROLADORIA/FINANÇAS-ALMOXARIFADO
WILTON GODOFREDO DE MELO-ASSIST ADMINISTRATIVO- 16. Assistente ;DANIELLY LIMA DA SILVA BRAGA-RECURSOS HUMANOS-DOCUMENTAÇÃO
FABIANA SANTOS MENDES FERREIRA-ASSIST ADMINISTRATIVO- 16. Assistente ;VALDENEI FRANCA-OPERAÇÕES-CLIENTE

`;
      break;
    case "modelo11":
      conteudo = `
MARCIO ANDRE MOSCOSO DA ROCHA-DIRETOR COMERCIAL- 03. Diretor ;AUGUSTO CESAR LOUREIRO DA SILVA-COMERCIAL-COMERCIAL
LIA SILVA DOS SANTOS-GER FINANCEIRO- 05. Gerente ;MARCIO ANDRE MOSCOSO DA ROCHA-FINANCEIRO-FATURAMENTO
ROSELI GAMA NORONHA DA MOTTA-GER RECURSOS HUMANOS- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-RECURSOS HUMANOS-RECURSOS HUMANOS
ROSELI GAMA NORONHA DA MOTTA-GER RECURSOS HUMANOS- 05. Gerente ;AUGUSTO CESAR LOUREIRO DA SILVA-RECURSOS HUMANOS-RECURSOS HUMANOS
BIANCA CENEDESI TOLA-COORD CONTROLADORIA E FINANCAS- 06. Coord. / Esp. ;CLODOVIRGES NEVES DE AMORIM JUNIOR-CONTROLADORIA/FINANÇAS-CONTROLADORIA
KLEITON DOS SANTOS COSTA-COORD(A)COMERCIAL- 06. Coord. / Esp. ;MARCIO ANDRE MOSCOSO DA ROCHA-COMERCIAL-COMERCIAL
LEURI JEFFERSON DE ANDRADE MORAES-ENG SEG TRABALHO- 08. Analista ;AMARILIS FELIPE FONSECA FERREIRA AYRES-SESMT-SEGURANÇA DO TRABALHO
LEON GABRIEL BRASIL COSTA-ENGENHEIRO AMBIENTAL- 08. Analista ;MARCIO ANDRE MOSCOSO DA ROCHA-COMERCIAL-COMERCIAL
LEURI JEFFERSON DE ANDRADE MORAES-ENG SEG TRABALHO- 08. Analista ;AMARILIS FELIPE FONSECA FERREIRA AYRES-SESMT-SEGURANÇA DO TRABALHO
HAILTON BRITO OLIVEIRA-TEC ENFERMAGEM DO TRABALHO- 10. Técnico ;AMARILIS FELIPE FONSECA FERREIRA AYRES-SESMT-MEDICINA DO TRABALHO
RODRIGO MORAES DOS ANJOS-TEC SEG DO TRABALHO- 10. Técnico ;LEURI JEFFERSON DE ANDRADE MORAES-SESMT-SEGURANÇA DO TRABALHO
EMELY LUIZA MACEDO FERREIRA-TEC SEG DO TRABALHO- 10. Técnico ;LEURI JEFFERSON DE ANDRADE MORAES-SESMT-SEGURANÇA DO TRABALHO
LUIZA VIANA SOUTO-TEC SEG DO TRABALHO- 10. Técnico ;LEURI JEFFERSON DE ANDRADE MORAES-SESMT-SEGURANÇA DO TRABALHO
DANIELE DAMASCENO MACEDO-ANL ADMINISTRATIVO PL- 08. Analista ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-COMPRAS
FABIO ROGERIO GAMA DE OLIVEIRA-ANL COMERCIAL SR- 08. Analista ;MARCIO ANDRE MOSCOSO DA ROCHA-COMERCIAL-COMERCIAL
RITA CRISTINA DA SILVA MATOS-ANL DA QUALIDADE SR- 08. Analista ;BIANCA CENEDESI TOLA-CONTROLADORIA/FINANÇAS-QUALIDADE
VITORIA KALLYNA DA SILVA HOLLES-ANL ADMINISTRATIVO PL- 08. Analista ;AUGUSTO CESAR LOUREIRO DA SILVA-APOIO OPERACIONAL-COMPRAS
CARLA TATIANA DA SILVA PESSOA-ANL COMERCIAL PL- 08. Analista ;MARCIO ANDRE MOSCOSO DA ROCHA-COMERCIAL-COMERCIAL
ANA PAULA DA SILVA FERREIRA-ANL CONTROLADORIA JR- 08. Analista ;BIANCA CENEDESI TOLA-CONTROLADORIA/FINANÇAS-CONTROLADORIA
FERNANDA TOCANTINS SILVA-ANL ADMINISTRATIVO JR- 08. Analista ;AMARILIS FELIPE FONSECA FERREIRA AYRES-APOIO OPERACIONAL-OPERAÇÕES
EDUARDO PEREIRA DE ALMEIDA-ANL COMERCIAL JR- 08. Analista ;MARCIO ANDRE MOSCOSO DA ROCHA-COMERCIAL-COMERCIAL
CAMILA CUNHA DA SILVA-ASSIST ADM DE PESSOAL- 16. Assistente ;ROSELI GAMA NORONHA DA MOTTA-RECURSOS HUMANOS-FOPAG
ROMULO CEZAR OLIVEIRA DE SOUZA-ASSIST ADMINISTRATIVO- 16. Assistente ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-FROTAS
TATIANY DO CARMO SOARES MEDEIROS-ASSIST FINANCEIRO- 16. Assistente ;LIA SILVA DOS SANTOS-FINANCEIRO-FATURAMENTO
MARIA NATALIA GOMES DA SILVA-ASSIST FINANCEIRO- 16. Assistente ;LIA SILVA DOS SANTOS-FINANCEIRO-FATURAMENTO
LAILA RAISSA DA SILVA BARBOSA-ASSIST ADM DE PESSOAL- 16. Assistente ;ROSELI GAMA NORONHA DA MOTTA-RECURSOS HUMANOS-FOPAG+BENEFÍCIOS
MARIA DE NAZARE FURTADO SERRAO-ASSIST FINANCEIRO- 16. Assistente ;LIA SILVA DOS SANTOS-FINANCEIRO-DOCUMENTAÇÃO
KAROLINE DA COSTA RODRIGUES-ASSIST RH- 16. Assistente ;ROSELI GAMA NORONHA DA MOTTA-RECURSOS HUMANOS-R&S+ADMISSÃO
LUANA KAROLINA MELO SANTOS-ASSIST ADM DE PESSOAL- 16. Assistente ;ROSELI GAMA NORONHA DA MOTTA-RECURSOS HUMANOS-DESLIGAMENTO
FHELYPE MARTINS CAVALCANTE-ASSIST ADMINISTRATIVO- 16. Assistente ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-COMPRAS
SABRINA GOMES MARTINS-ASSIST ADMINISTRATIVO- 16. Assistente ;ELKE EMANUELLY PEREIRA DOS SANTOS -APOIO OPERACIONAL-PONTO-MESA DE OPERAÇÕES
ADRIANA CONCEICAO DE SOUSA-ASSIST ADMINISTRATIVO- 16. Assistente ;ELKE EMANUELLY PEREIRA DOS SANTOS -APOIO OPERACIONAL-PONTO-MESA DE OPERAÇÕES
SAMUEL DE SOUSA FERREIRA-ASSIST ADMINISTRATIVO- 16. Assistente ;ELKE EMANUELLY PEREIRA DOS SANTOS -APOIO OPERACIONAL-PONTO-MESA DE OPERAÇÕES
CHRISTIAN CAIQUE ROSA DE SOUZA-ASSIST ADMINISTRATIVO- 16. Assistente ;ELKE EMANUELLY PEREIRA DOS SANTOS -APOIO OPERACIONAL-DAO
MARCOS MESSIAS DOS SANTOS MORAES-ASSIST ADMINISTRATIVO- 16. Assistente ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-ALMOXARIFADO
ELAIZE GARCIA MADEIRA-ASSIST ADMINISTRATIVO- 16. Assistente ;AMARILIS FELIPE FONSECA FERREIRA AYRES-APOIO OPERACIONAL-DAO
CARLA DO S RABELO DE ASSUNCAO BENCHIMOL-AUX ADMINISTRATIVO- 17. Auxiliar ;LEURI JEFFERSON DE ANDRADE MORAES-SESMT-SESMT
DENISON ROCHA LOPES-OFICIAL DE REDE- 13.Operação ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-TI
JOSE RIBAMAR GOMES MACEDO-FISCAL- 13.Operação ;AMARILIS FELIPE FONSECA FERREIRA AYRES-APOIO OPERACIONAL-OPERAÇÕES
JOEL ALEXANDRE PRUDENTE DA SILVA-TECNICO EM MANUTENCAO PREDIAL - 10. Técnico ;AMARILIS FELIPE FONSECA FERREIRA AYRES-APOIO OPERACIONAL-OPERAÇÕES
JOAO MURILO RODRIGUES MENDES-ALMOXARIFE- 13.Operação ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-ALMOXARIFADO
CRISTIAN SANTANA MAGALHAES-OFFICE BOY- 13.Operação ;BIANCA CENEDESI TOLA-APOIO OPERACIONAL-OPERAÇÕES
`;
      break;
    case "modelo12":
      conteudo = `
THIAGO DINIZ SILVEIRA FOGACA-DIRETOR EFICIÊNCIA-  02. VP;FABIO SANDRINI BAPTISTA-EFICIÊNCIA-EFICIÊNCIA
MARIANA VIEIRA COIANAGUI-GERENTE SR SUPRIMENTOS- 04. Gerente Sr;THIAGO DINIZ SILVEIRA FOGACA-EFICIÊNCIA-SUPRIMENTOS
JOSE AURELIO MOSSON-GERENTE DE FACILITIES- 05. Gerente ;THIAGO DINIZ SILVEIRA FOGACA-FACILITIES-FACILITIES
FERNANDO NERIS DOS SANTOS-COORD COMPRAS- 06. Coord. / Esp. ;THIAGO DINIZ SILVEIRA FOGACA-DIRETOR EFICIÊNCIA-SUPRIMENTOS-SUPRIMENTOS
CLEBER MAURO CAPELLA-COORDENADOR DE FROTA-;JOSE AURELIO MOSSON-FACILITIES-FROTAS
RAFAEL KENJI IKEDA-ESPECIALISTA EM COMPRAS- 06. Coord. / Esp. ;FERNANDO NERIS DOS SANTOS-SUPRIMENTOS-SUPRIMENTOS
GABRIEL GUISILINI FRANCOZO-ANALISTA DE COMPRAS SR- 08. Analista ;FERNANDO NERIS DOS SANTOS-SUPRIMENTOS-SUPRIMENTOS
MARCO ANTONIO DE CASTRO-ANALISTA DE COMPRAS PL- 08. Analista ;FERNANDO NERIS DOS SANTOS-SUPRIMENTOS-SUPRIMENTOS
VITOR ANTONIO DE OLIVEIRA ARAUJO-ASSIST ADMINISTRATIVO- 16. Assistente ;ROBSON DE FARIAS-FACILITIES-ALMOXARIFADO
MARISELMA DA CRUZ HORA BRAZ-ASSIST ADMINISTRATIVO- 16. Assistente ;ROBSON DE FARIAS-FACILITIES-FACILITIES
JOSE ROGERIO TOLENTINO MARQUES-AUX ALMOXARIFE- 13.Operação ;ROBSON DE FARIAS-FACILITIES-ALMOXARIFADO
MARIA FERNANDA DE ASSIS-AUX ADMINISTRATIVO- 17. Auxiliar ;JOSE AURELIO MOSSON-FACILITIES-FACILITIES
LEONARDO FELIX DOS SANTOS-AUX DE MANUTENCAO- 13.Operação ;ROSANGELA VIEIRA DA SILVA-FACILITIES-FACILITIES
TONY DA SILVA-AUX ALMOXARIFE- 13.Operação ;ROBSON DE FARIAS-FACILITIES-ALMOXARIFADO
MICHAEL SANTOS GOMES DE MENEZES-AUX ADMINISTRATIVO- 17. Auxiliar ;CLEBER MAURO CAPELLA-FACILITIES-FACILITIES
PATRICIA BARBOSA DOS SANTOS-AUX ADMINISTRATIVO- 17. Auxiliar ;ROBSON DE FARIAS-FACILITIES-ALMOXARIFADO
ROBSON DE FARIAS-SUPERVISOR(A) ALMOXARIFADO- 07. Supervisor ;JOSE AURELIO MOSSON-FACILITIES-ALMOXARIFADO
ROSANGELA VIEIRA DA SILVA-SUPERVISOR (A)- 07. Supervisor ;JOSE AURELIO MOSSON-FACILITIES-FACILITIES
PEDRO GOMES NETO-MECANICO DE MANUTENÇÃO- 13.Operação ;JOSE AURELIO MOSSON-FACILITIES-FACILITIES
EDSON CALIXTO DA SILVA-MECANICO DE MANUTENÇÃO- 13.Operação ;JOSE AURELIO MOSSON-FACILITIES-FACILITIES
GIL DE SIQUEIRA-MECANICO DE MANUTENÇÃO- 13.Operação ;JOSE AURELIO MOSSON-FACILITIES-FACILITIES

`;
      break;
  }

  document.getElementById("entrada").value = conteudo.trim();
}
    function gerarOrganograma() {
      const texto = document.getElementById("entrada").value;
      const linhas = texto.trim().split("\n");
      const nodes = [];

      linhas.forEach(linha => {
        if (linha.trim() === "") return;

        const partes = linha.trim().split(";");
        const dados = partes[0].trim().split("-");
        const posDadosExtra = partes[1]?.trim().split("-") || [];

        const nome = dados[0]?.trim();
        const cargo = dados[1]?.trim() || "";
        const classificacao = dados[2]?.trim() || "";
        const chefe = posDadosExtra[0]?.trim();
        const departamento = posDadosExtra[1]?.trim() || "";
        const secao = posDadosExtra[2]?.trim() || "";

        if (!nome) return;

        const node = {
          id: nome,
          name: nome,
          cargo,
          classificacao,
          title: `${cargo} - ${classificacao}`,
          departamento,
          secao
        };

        if (chefe && chefe !== nome) {
          node.pid = chefe;
        }

        nodes.push(node);
      });

      const agora = new Date();
      const formatado = agora.toLocaleString("pt-BR", {
        day: "2-digit",
        month: "2-digit",
        year: "numeric",
        hour: "2-digit",
        minute: "2-digit",
        second: "2-digit"
      });
      document.getElementById("ultimaAtualizacao").innerText = `Última geração: ${formatado}`;
      document.getElementById("organograma").innerHTML = "";

      OrgChart.templates.meuTemplate = Object.assign({}, OrgChart.templates.ana);
      OrgChart.templates.meuTemplate.size = [250, 100];
      OrgChart.templates.meuTemplate.node =
        '<rect x="0" y="0" width="250" height="100" rx="12" ry="12" fill="#ffffff" stroke-width="1" stroke="#007e8a"></rect>';
      OrgChart.templates.meuTemplate.field_0 =
        '<text data-width="230" data-text-overflow="multiline" style="font-size: 16px; font-weight: bold;" fill="#009da8" x="125" y="40" text-anchor="middle">{val}</text>';
      OrgChart.templates.meuTemplate.field_1 =
        '<text data-width="230" style="font-size: 12px;" fill="#009da8" x="125" y="80" text-anchor="middle">{val}</text>';

      const chart = new OrgChart(document.getElementById("organograma"), {
        nodes,
        template: "meuTemplate",
        enableSearch: true,
        searchFields: ["name", "cargo", "classificacao", "secao"],
        nodeMenu: false,
        enableDetailsView: false,
        showDetails: false,
        nodeBinding: {
          field_0: "name",
          field_1: "title"
        },
        nodeClick: function (sender, args) {
          const dados = args.node;
          document.getElementById("modal-nome").innerText = dados.name || "";
          document.getElementById("modal-cargo").innerText = dados.cargo || "";
          document.getElementById("modal-classificacao").innerText = dados.classificacao || "";
          document.getElementById("modal-departamento").innerText = dados.departamento || "";
          document.getElementById("modal-secao").innerText = dados.secao || "";
          document.getElementById("modal").style.display = "flex";
        }
      });
    }

     fetch("organograma.json")
  .then(res => res.json())
  .then(data => {
    const chart = new OrgChart(document.getElementById("organograma"), {
      nodes: data,
      template: "meuTemplate", // opcional, se quiser aplicar seu template customizado
      enableSearch: true,
      searchFields: ["name", "cargo", "classificacao", "secao"],
      enableDetailsView: false,
      showDetails: false,
      nodeBinding: {
        field_0: "name",
        field_1: "title"
      },
      tooltip: {
        enabled: true,
        template: function (data) {
          return `
            <div class="custom-tooltip">
              <div class="tooltip-header">${data.name}</div>
              <div class="tooltip-line"><strong>Cargo:</strong> ${data.cargo || '-'}</div>
              <div class="tooltip-line"><strong>Classificação:</strong> ${data.classificacao || '-'}</div>
              <div class="tooltip-line"><strong>Departamento:</strong> ${data.departamento || '-'}</div>
              <div class="tooltip-line"><strong>Seção:</strong> ${data.secao || '-'}</div>
              <div class="tooltip-line"><strong>Chefia:</strong> ${data.pid || 'Nível mais alto'}</div>
            </div>
          `;
        }
      },
      nodeClick: function (sender, args) {
        const dados = args.node;
        document.getElementById("modal-nome").innerText = dados.name || "";
        document.getElementById("modal-cargo").innerText = dados.cargo || "";
        document.getElementById("modal-classificacao").innerText = dados.classificacao || "";
        document.getElementById("modal-departamento").innerText = dados.departamento || "";
        document.getElementById("modal-secao").innerText = dados.secao || "";
        document.getElementById("modal").style.display = "flex";
      }
    });
  });

    document.addEventListener("DOMContentLoaded", () => {
      document.getElementById("fechar-modal").onclick = () => {
        document.getElementById("modal").style.display = "none";
      };
      document.getElementById("modal").onclick = e => {
        if (e.target.id === "modal") {
          document.getElementById("modal").style.display = "none";
        }
      };
    });